name: 'Build & Run'
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Run original Spigot-BuildTools (1.8)

        run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
          java -jar BuildTools.jar --rev 1.8 --compile Spigot

      - name: Compile 1.8 spigot version
        run: mvn clean package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Plugin JAR
          path: |
            *.jar