name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.8.8
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Plugin JAR
          path: |
            *.jar